### ISSUE TITLE
Failed to load extract-url on Android. 

### ISSUE THREAD

**Issue by suny24x7** [trashhalo/obsidian-extract-url#14]
Just saw this [thread ](https://forum.obsidian.md/t/extract-url-plugin-mobile-support/23664) and found that extrac-url is now available for mobile. But after installing plugin is failing to load.

![Screenshot_20210914-114949](https://user-images.githubusercontent.com/68751169/133202670-f9cb04f9-4334-45df-a5df-64bf807955ff.png)

Device :	Xiaomi Mi A1
Version : Android 9

**Comment by trashhalo** [comment]
Oh no! Thanks for letting me know. Do you know if you are using the latest version of the obsidian app?

**Comment by suny24x7** [comment]
Yes. I'm on latest version. v1.0.4

**Comment by suny24x7** [comment]
Problem solved after reinstalling the plugin.
