### ISSUE TITLE
Imported URLs don't store full url of links

### ISSUE THREAD

**Issue by quintrino** [trashhalo/obsidian-extract-url#2]
Hi, 

I just tested your plugin and when importing https://en.wikipedia.org/wiki/Obsidian it appears that instead of storing the full urls for the links in the article, it's just getting part of the links. 

```**Obsidian** (/əbˈsɪdiən/) is a naturally occurring [volcanic glass](/wiki/Volcanic_glass) formed as an [extrusive](/wiki/Extrusive_rock)[igneous rock](/wiki/Igneous_rock).<sup><a href="#cite_note-4">[4]</a></sup>```

which means that if I click on the [igneous rock] link, instead of it taking me to Wikipedia's page on igneous rock, it just creates a new note called igneous_rock in a new folder called wiki. 

I just wanted to check if this is the desired behaviour or not. 

Thanks for making such a great plugin! 😄

**Comment by trashhalo** [comment]
Ah ya good catch! Not desired behavior. I would have expected it to link externally to the other pages. I'll take a look at fixing this!

**Comment by trashhalo** [comment]
@quintrino Just published 0.4.0 that has a fix for relative url! Thanks for the report.

**Comment by quintrino** [comment]
Haha, I think this has to be the fastest reply on a github issue I've ever seen!
