### ISSUE TITLE
Custom template for Youtube

### ISSUE THREAD

**Issue by quintrino** [trashhalo/obsidian-extract-url#3]
One possible idea for extract url would be a custom format for youtube links. 

At the moment running it on a Youtube video doesn't seem extract the description or embed the video. 

For example https://www.youtube.com/watch?v=qqsNNTkhK5Y

Has stuff in his description
```
▬▬▬▬▬▬▬▬▬▬ ► CHECK THESE OUT ◀︎▬▬▬▬▬▬▬▬▬▬
📧️ NEWSLETTER: https://bryanjenkstech.ck.page/d4ec07...​
💬 DISCORD:  https://discord.gg/MxCVshN​
🗣️ SOCIALS:  https://streamerlinks.com/tallguyjenks
etc
```

Just an idea that might interest you. :)

**Comment by trashhalo** [comment]
Great idea! I think thats going to be the next phase of this project. Custom conversions for stuff like youtube, twitter, etc.

**Comment by quintrino** [comment]
I'll have a link about other websites that could benefit from custom formats.

**Comment by trashhalo** [comment]
Done as of 0.6+.

Also bunch of websites now work. Check out all the features released here https://forum.obsidian.md/t/extract-url-plugin-0-7-linked-documents-media-support-and-grab-urls-from-the-clipboard/16258?u=trashhalo
