### ISSUE TITLE
Choose default link for import if none selected

### ISSUE THREAD

**Issue by quintrino** [trashhalo/obsidian-extract-url#4]
Just another feature request that might be interesting. 

If you have a link in your YAML frontmatter
---
link: https://en.wikipedia.org/wiki/Obsidian
---

if would be good to be able to run the command without having the link selected ( I guess you could also set the yaml key to use in the plugin config (link vs reference vs webpage, etc)) and it would then put the content whereever the cursor is.

**Comment by trashhalo** [comment]
Done as of 0.5.0! you can read how to do this in the readme. https://github.com/trashhalo/obsidian-extract-url
