### ISSUE TITLE
Adding Youtube text

### ISSUE THREAD

**Issue by q7z** [trashhalo/obsidian-extract-url#5]
Is it possible to extract the video description from the text too? That would be phenomenal.

**Comment by quintrino** [comment]
I was going to suggest title too, but it already does this by default. 

Maybe the channel name?

**Comment by trashhalo** [comment]
Doing a little research this weekend. I found a path that will give us description and channel name, but it would require you to install `youtube-dl` on your system. Do you think that would be okay?

**Comment by quintrino** [comment]
I already have it installed so fine by me. 👍

**Comment by q7z** [comment]
Yep! That works. It is a power user feature already so it's not unreasonable to expect that dependency.

**Comment by trashhalo** [comment]
![Screenshot from 2021-04-24 20 20 04](https://user-images.githubusercontent.com/177491/115976313-b8ad8d80-a53a-11eb-82b9-20258ec68bab.png)

:boom: 0.8.0 youtube-dl powered details

**Comment by q7z** [comment]
@trashhalo  Thanks so much for this! Is there any way I can use this on a playlist?
