### ISSUE TITLE
No longer able to extract full text? 

### ISSUE THREAD

**Issue by quintrino** [trashhalo/obsidian-extract-url#6]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/7043587/114591278-120cf580-9ccd-11eb-8e0a-90f095a62758.png">
<img width="773" alt="image" src="https://user-images.githubusercontent.com/7043587/114591335-1fc27b00-9ccd-11eb-86f2-5bd3ad385450.png">

It looks like the option to extract the full contents, either from a highlighted link or the yaml are no longer showing. 

I'm using 0.7.0 of the plugin and 0.11.13 of Obsidian. 
I tried restarting obsidian and then uninstalling and reinstalling the plugin but it still seems to be missing the extact full contents from highlighted / yaml link.

**Comment by trashhalo** [comment]
NICK!! I am so sorry :( I see that too. Let me see what I can do. I really got to add test cases.

**Comment by trashhalo** [comment]
Fixed as of 0.7.1 please update :pray:

**Comment by quintrino** [comment]
Perfect. Installed now and it's working again!
