### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by ankushg** [trashhalo/obsidian-extract-url#9]
Does this work on mobile? Any blocking issues from getting it to work properly?

**Comment by trashhalo** [comment]
The main thing holding it back from being mobile friendly is the plugin is running in the a render process that is enforcing CORS headers. I think @lishid said on the discord he was going to add a request method that bypassed this. I'll hold this open until that happens.

**Comment by terretta** [comment]
**+1** 

On iOS I use a Shortcut to grab URLs into Bear / Ulysses / Apple Notes as Markdown, but doesn’t play well with Obsidian.  

To replace all those with Obsidian as is my goal, I really need a mobile tool for _URL to note body as markdown_, with as few steps as possible.  Perhaps ideally into a template, so I can have my own filename, title, and attribution boilerplate, followed by original body as markdown.  (I could also see that being config, e.g. filename prepend/postpend date time format to title, attribution boilerplate, boilerplate above / below content, and divider.  Some plugins use this config approach.)

Should we be asking on Discord for that request method to be prioritized?

**Comment by trashhalo** [comment]
It's been a couple of months. Let me look at what's available this weekend and see if its become possible.

**Comment by lishid** [comment]
A mechanism to fetch without CORS restrictions will be included in one of the next versions. Stay tuned!

**Comment by trashhalo** [comment]
Mobile support has landed in 0.9.0!!
